# Generated by Django 3.2 on 2021-04-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_auto_20210423_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this resource.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this resource.', max_length=500),
        ),
    ]
