# Generated by Django 3.2 on 2021-04-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0011_auto_20210425_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='listed',
            field=models.BooleanField(default=True),
        ),
    ]
