# Generated by Django 3.1.8 on 2021-04-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0003_auto_20210419_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
