# Generated by Django 3.2 on 2021-05-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0005_taggeditem_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'ordering': ['tag__slug']},
        ),
    ]
