# Generated by Django 3.1.8 on 2021-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210417_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Limited Markdown supported'),
        ),
        migrations.AlterField(
            model_name='user',
            name='feature_as_artist',
            field=models.BooleanField(default=False, help_text='Select this to be included in list of artists.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Optional, to show a different name than your username.', max_length=255, verbose_name='Display Name'),
        ),
    ]
