# Generated by Django 3.2 on 2021-05-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_publish_uploads',
            field=models.BooleanField(default=False, help_text='Select this to make new uploads publicly listed.'),
        ),
    ]
