# Generated by Django 3.1.7 on 2021-04-14 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetch',
            name='file',
            field=models.ForeignKey(blank=True, help_text='File that was fetched, when finished, if successful.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fetches', to='repo.file'),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When the fetch finished.', null=True),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the fetch started.', null=True),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='success',
            field=models.BooleanField(blank=True, help_text='Whether the fetch succeeded.', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('M', 'Module'), ('P', 'Project')], help_text='Type of file, if known.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added the resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_good_fetch',
            field=models.ForeignKey(blank=True, help_text='Most recent fetch that succeeded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='repo.fetch'),
        ),
        migrations.AlterField(
            model_name='location',
            name='most_recent_file',
            field=models.ForeignKey(blank=True, help_text='File ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='repo.file'),
        ),
    ]
