# Generated by Django 3.1.8 on 2021-04-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20210414_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='When the file was last accessed.', null=True),
        ),
    ]
